// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TieredEntity.Web.AppDb;

namespace TieredEntity.Web.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20190504184646_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TieredEntity.Web.Models.ALDutyPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NextId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("AlDutyPositions");
                });

            modelBuilder.Entity("TieredEntity.Web.Models.ALJobRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NextId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("AlJobRoles");
                });

            modelBuilder.Entity("TieredEntity.Web.Models.NSDutyPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Left");

                    b.Property<int>("Right");

                    b.Property<string>("Title");

                    b.Property<int?>("TreeId");

                    b.HasKey("Id");

                    b.ToTable("NsDutyPositions");
                });

            modelBuilder.Entity("TieredEntity.Web.Models.NSJobRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Left");

                    b.Property<int>("Right");

                    b.Property<string>("Title");

                    b.Property<int?>("TreeId");

                    b.HasKey("Id");

                    b.ToTable("NsJobRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
